# Deploy the kyc service on NixOS as an OCI container. The only input is
# environment:
#
#   1. copy this file into the host configuration and import it
#   2. write the environment file (the ../.env.example contract) to
#      /run/secrets/kyc.env - root-owned, 0400, or generated by
#      agenix / sops-nix
#   3. nixos-rebuild switch
#
# Capabilities follow DATABASE_URL in the env file: leave it unset for
# access tokens alone, point it at Postgres for session orchestration.
# `migrate` applies the schema once per database (commented block at the
# bottom).
#
# This template is written against the NixOS options as documented; it has
# not been run against a live NixOS host.

{ ... }:

{
  # Either backend works; podman is rootless-capable and needs no daemon.
  virtualisation.oci-containers.backend = "podman"; # or "docker"

  virtualisation.oci-containers.containers.kyc-service = {
    image = "ghcr.io/blinkbitcoin/kyc-service:latest"; # pin :<version> in production
    autoStart = true;

    # The whole configuration, as on every other target.
    environmentFiles = [ "/run/secrets/kyc.env" ];

    environment = {
      # The image already defaults to this; naming it here is the reminder
      # that a production posture refuses the sandbox token and the mock
      KYC_ENV = "production";
      PORT = "5100";
      # Behind a reverse proxy, so the rate limits key on the real client
      TRUST_PROXY = "true";
    };

    ports = [ "5100:5100" ];

    # Publish on the loopback interface only when a reverse proxy fronts it:
    # ports = [ "127.0.0.1:5100:5100" ];
    extraOptions = [ "--health-cmd=wget -qO- http://127.0.0.1:5100/health" ];
  };

  # --- Session orchestration (optional) -----------------------------------
  # Set DATABASE_URL in the env file, give the container a database, and
  # apply the schema once per database.
  #
  # A database on the host (services.postgresql.enable = true; and a
  # postgresql.ensureDatabases / ensureUsers pair) is reached from the
  # container over the host address, so the container also needs
  # extraOptions = [ "--network=host" ]; or an explicit podman network. A
  # second oci-containers.containers entry running postgres:15 is the
  # self-contained alternative.
  #
  # The migrate one-shot, run once per database (and after an upgrade that
  # adds a migration), from a root shell on the host:
  #
  #   podman run --rm --env-file /run/secrets/kyc.env \
  #     ghcr.io/blinkbitcoin/kyc-service:latest node dist/node.js migrate
}
